version: '3.3'
services:
  arelle-base:
    image: arelle-base
    build:
      context: docker/Arelle
    command: '/bin/true'
  arelle:
    image: arelle
    build:
      context: docker/Arelle-custom
    volumes:
      - ./arelle-workdir:/root/.config/arelle
      - ./filings:/usr/src/app/filings
    ports:
      - "8080:8080"

  postgres:
    build:
      context: docker/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=arelle_pwd
      - POSTGRES_DB=arelle_db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: arelle@xbrl.org
      PGADMIN_DEFAULT_PASSWORD: arelle_pwd
    ports:
      - 8001:80
    depends_on:
      - postgres
